import React, { useState } from 'react';
import jsPDF from 'jspdf';
import './PetDietPlans.css';

const PetDietPlans = () => {
  const [species, setSpecies] = useState('');
  const [breed, setBreed] = useState('');
  const [petName, setPetName] = useState('');
  const [showDietDialog, setShowDietDialog] = useState(false);
  const [isLoading, setIsLoading] = useState(false);

  const handleSpeciesChange = (e) => setSpecies(e.target.value);
  const handleBreedChange = (e) => setBreed(e.target.value);

  const handlePetNameChange = (e) => {
    const value = e.target.value;
    if (/^[A-Za-z\s]*$/.test(value)) {
      setPetName(value);
    }
  };

  const getDietPlan = () => {
    if (species.toLowerCase().includes('german shepherd')) {
      return {
        food: 'High-quality dry kibble with meat protein',
        amount: '2-3 cups daily',
        frequency: 'Twice a day',
        notes: 'Include lean meat supplements and vegetables',
      };
    }
    return {
      food: 'General pet food',
      amount: '1-2 cups daily',
      frequency: 'Once or twice a day',
      notes: 'Consult vet for specific needs',
    };
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    setIsLoading(true);
    setTimeout(() => {
      setShowDietDialog(true);
      setIsLoading(false);
    }, 1000);
  };

  const handleDownloadPdf = () => {
    try {
      if (!petName || !species || !breed) {
        alert('Please complete all pet information first');
        return;
      }
  
      const doc = new jsPDF();
      const diet = getDietPlan();
      
      // Set document properties
      doc.setProperties({
        title: `${petName}'s Diet Plan`,
        subject: 'Pet Nutrition Guide',
        author: 'BawwaLK Pet Care'
      });
  
      // Add header
      doc.setFontSize(22);
      doc.setTextColor(45, 55, 72); // Dark blue-gray
      doc.setFont('helvetica', 'bold');
      doc.text(`Diet Plan for ${petName}`, 105, 20, { align: 'center' });
  
      // Add pet information
      doc.setFontSize(14);
      doc.text(`Species: ${species}`, 20, 40);
      doc.text(`Breed: ${breed}`, 20, 50);
  
      // Add diet plan section header
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(249, 115, 22); // Orange
      doc.text('Recommended Diet Plan', 20, 70);
  
      // Add diet details with proper formatting
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(0, 0, 0); // Black
      
      // Use proper bullet points and spacing
      doc.text('• Food: ' + diet.food, 25, 85);
      doc.text('• Amount: ' + diet.amount, 25, 95);
      doc.text('• Frequency: ' + diet.frequency, 25, 105);
      doc.text('• Notes: ' + diet.notes, 25, 115);
  
      // Add footer
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100); // Gray
      doc.text('Generated by BawwaLK Pet Care', 105, 280, { align: 'center' });
  
      // Save the PDF
      doc.save(`${petName.replace(/\s+/g, '_')}_Diet_Plan.pdf`);
      
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Failed to generate PDF. Please try again.');
    }
  };

  const closeDialog = () => {
    setShowDietDialog(false);
  };

  return (
    <div className="pet-diet-plans">
      <div className="pet-diet-header">
        <h1>Personalized Pet Diet Plans</h1>
        <p>Create a customized nutrition plan for your furry friend</p>
      </div>

      <form onSubmit={handleSubmit} className="diet-form">
        <div className="form-group">
          <label>Pet Name</label>
          <input
            type="text"
            value={petName}
            onChange={handlePetNameChange}
            placeholder="e.g. Max"
            required
          />
        </div>

        <div className="form-group">
          <label>Species</label>
          <input
            type="text"
            value={species}
            onChange={handleSpeciesChange}
            placeholder="e.g. Dog, Cat"
            required
          />
        </div>

        <div className="form-group">
          <label>Breed</label>
          <input
            type="text"
            value={breed}
            onChange={handleBreedChange}
            placeholder="e.g. German Shepherd"
            required
          />
        </div>

        <div className="form-actions">
          <button type="submit" className="submit-btn" disabled={isLoading}>
            {isLoading ? (
              <span className="spinner"></span>
            ) : (
              'Generate Diet Plan'
            )}
          </button>
          {showDietDialog && (
            <button type="button" className="download-btn" onClick={handleDownloadPdf}>
              Download PDF
            </button>
          )}
        </div>
      </form>

      {showDietDialog && (
        <div className="diet-dialog">
          <div className="diet-dialog-content">
            <button className="close-btn" onClick={closeDialog}>
              &times;
            </button>
            <div className="dialog-header">
              <h2>Diet Plan for {petName}</h2>
              <div className="pet-icon">🐕</div>
            </div>
            
            <div className="diet-details">
              <div className="detail-item">
                <span className="detail-label">Species:</span>
                <span className="detail-value">{species}</span>
              </div>
              <div className="detail-item">
                <span className="detail-label">Breed:</span>
                <span className="detail-value">{breed}</span>
              </div>
              
              <h3 className="section-title">Recommended Diet</h3>
              
              <div className="diet-item">
                <span className="diet-icon">🍗</span>
                <div>
                  <h4>Food</h4>
                  <p>{getDietPlan().food}</p>
                </div>
              </div>
              
              <div className="diet-item">
                <span className="diet-icon">⚖️</span>
                <div>
                  <h4>Amount</h4>
                  <p>{getDietPlan().amount}</p>
                </div>
              </div>
              
              <div className="diet-item">
                <span className="diet-icon">⏱️</span>
                <div>
                  <h4>Frequency</h4>
                  <p>{getDietPlan().frequency}</p>
                </div>
              </div>
              
              <div className="diet-item">
                <span className="diet-icon">📝</span>
                <div>
                  <h4>Notes</h4>
                  <p>{getDietPlan().notes}</p>
                </div>
              </div>
            </div>
            
            <button className="download-full-btn" onClick={handleDownloadPdf}>
              Download Full Plan
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default PetDietPlans;